### ISSUE TITLE
griffinlim for Harmonix 

### ISSUE THREAD

**Issue by deyituo** [zhaojw1998/Beat-Transformer#1]
Can you share the script for Harmonix reconstruction? or the argument for the function below ?
https://librosa.org/doc/main/generated/librosa.griffinlim.html

**Comment by zhaojw1998** [comment]
I have uploaded your requested script to "./processing_codes/harmonix_mel2wav.py". Please note that the reconstruction is NOT lossless (in fact very lossful, but still acceptable for the beat tracking task).

**Comment by deyituo** [comment]
em... it seems lossful.. but the original youtube urls/alignment scripts are not enough to reconstrution.
