### ISSUE TITLE
full_beat_annotation.npz missing

### ISSUE THREAD

**Issue by asdf2adsfad** [zhaojw1998/Beat-Transformer#10]
Hi, 

I would like to kindly remind that you might forgot to upload full_beat_annotation.npz, so there is no way to train from scratch with the 33GB npz file.

Thank you!

**Comment by zhaojw1998** [comment]
> Hi,
> 
> I would like to kindly remind that you might forgot to upload full_beat_annotation.npz, so there is no way to train from scratch with the 33GB npz file.
> 
> Thank you!

Hi, the file you requested is already in the [data folder](https://github.com/zhaojw1998/Beat-Transformer/tree/main/data). Please kindly let me know if you find any problem with this file.

**Comment by asdf2adsfad** [comment]
Oh I am terribly sorry, my bad
