### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by LeeYaNam** [zhaojw1998/Beat-Transformer#12]
![image](https://user-images.githubusercontent.com/94519631/229457832-6955e647-0ed2-4639-bf74-db2f59d6201c.png)
when I want to download this dataset via Google Chrome,It says I'm banned from downloading
![image](https://user-images.githubusercontent.com/94519631/229458761-dbe5a187-a080-4b3f-b610-5b12c0184eb3.png)

**Comment by zhaojw1998** [comment]
> 

My colleagues and I tested the downloading and it worked for us. Could you give it another try with a stable network, and perhaps use a different browser?

**Comment by LeeYaNam** [comment]
Ok,thank you! I'll try again. Maybe there's another way to download it? By the way, is this 33G file an initial audio file or pre-processed image data? I'd like to know the specific type of this file.

**Comment by zhaojw1998** [comment]
> Ok,thank you! I'll try again. Maybe there's another way to download it? By the way, is this 33G file an initial audio file or pre-processed image data? I'd like to know the specific type of this file.

This 33GB file is pre-processed spectrogram data. Each piece is of shape (5, time, frequency_bin), where "5" refers to five demixed channels. If you wish to get the original audio, please refer to [this guidance](https://github.com/zhaojw1998/Beat-Transformer#audio-data).

**Comment by LeeYaNam** [comment]
thank you!
