### ISSUE TITLE
About the meaning of "the non-causal and causal components of the window"

### ISSUE THREAD

**Issue by moonryul** [zhaojw1998/Beat-Transformer#20]
Thanks for the wonder paper and work.

I am reading the paper, I have two questions.

1. I read:
In our work, we inherit the fashion of multi-task learning and the use of DBN, while proposing a novel Transformer **encoder** architecture to replace TCN.

=> I guess that "Transformers" mentioned through out the paper are encoder-only Transformers?, even though they are simply called "transformers"? 

2. The following paragraph puzzles me greatly:
------------------
3.1.2 Dilated Self-Attention (DSA)

An illustration of DSA is shown in Figure 1. DSA is computed over a short window of size lwin = m + n + 1,
where m and n are the length of non-causal and causal
components of the window (in Figure 1, m = n = 2).
Each Transformer layer has a dilation rate r > 1, and r
increases exponentially as the layer goes deeper.
---
. Specifically, i + rk
refers to the positions in K1:T that are attainable by Qi
under the dilated window of rate r.

=> Let us assume that r =1.
Then i+k = i-2, i-1 are past positions relative to position i.

Now, these positions are called "non-causal components of  [the 5x5] window:.
In what sense these positions are "non-causal" with respect to position i,
 considering that these positions are **past** relative to position i?

**Comment by zhaojw1998** [comment]
Hi, this is a Transformer Encoder. It is not autoregressive. Say the input has T frames, then the output would be T beat/downbeat predictions for each of the input frames.

**Comment by moonryul** [comment]
> Hi, this is a Transformer Encoder. It is not autoregressive. Say the input has T frames, then the output would be T beat/downbeat predictions for each of the input frames.

Hi, Zaho. Thanks for the quick answer to my first question.

I hope that you can find time to answer my second question as well.

Moon

**Comment by zhaojw1998** [comment]
Hi, in the case of r=1, i+k = i-2, i-1, i, i+1, i+2. We refer to i-2 and i-1 as “causal” component as it looks to the past of step i, and we call i+1 and i+2 “non-causal” component as it looks to the future of step i

**Comment by moonryul** [comment]
Hi. Thanks for the kind answer. Your answer makes sense.

But, then, 

There seems to be a typo in the paragraph prior to eq (3):

You wrote: 

DSA is computed over a short window of size l_win = m + n + 1, where m and n are the length of non-causal and causal components of the window. 

=> If you had written "l_win = m+n+1, where m and n are the length of causal and non-causal components of the window",
I would not have misunderstood you. 

moon
