### ISSUE TITLE
Can i have Hainsworth dataset？

### ISSUE THREAD

**Issue by obl1viate** [zhaojw1998/Beat-Transformer#5]
I can't find it from Internet now.

**Comment by zhaojw1998** [comment]
Hi. Drop me an email and I can share the dataset with u.

**Comment by obl1viate** [comment]
wzh135791113@gmail.com
Thanks!

**Comment by deyituo** [comment]
@zhaojw1998 share one copy?

tuodeyi@mail2.sysu.edu.cn

**Comment by zhaojw1998** [comment]
> @zhaojw1998 share one copy?
> 
> [tuodeyi@mail2.sysu.edu.cn](mailto:tuodeyi@mail2.sysu.edu.cn)

Sent already. Please check :)

**Comment by deyituo** [comment]
Thanks!
