### ISSUE TITLE
about the smc dataset

### ISSUE THREAD

**Issue by tricky61** [zhaojw1998/Beat-Transformer#6]
anyone knows how to download the smc dataset?
it seems the download url http://smc.inescporto.pt/research/data-2/ is invalid?

**Comment by deyituo** [comment]
@tricky61 the Dataset tag in https://joserzapata.github.io/publication/selective-sampling-beat-tracking/ ?

**Comment by tricky61** [comment]
@deyituo what is the download url?
I click the Dataset, but the url jumped to is https://bit.ly/33SlutJ, and it is unreachable.

**Comment by zhaojw1998** [comment]
> @deyituo what is the download url? I click the Dataset, but the url jumped to is https://bit.ly/33SlutJ, and it is unreachable.

I click this dataset link (https://bit.ly/33SlutJ) and it works for me. I'm using Chrome on a Windows system. Maybe VPN is also required?
