### ISSUE TITLE
Question regarding dilation for transformer

### ISSUE THREAD

**Issue by asdf2adsfad** [zhaojw1998/Beat-Transformer#8]
Hi,

Thanks for making the source open, it is really a great chance to learn from you!

After reading the paper, I got a simple question about the dilated transformer module. In the paper, it seemed that there's a dilation rate r that grows exponentially from 2^0 to 2^8, and the r are different across the layers. But when I read the code, I found that the idx variable used for initializing Demixed_DilatedTransformerModel was not utilized in dilation (please correct me if i am wrong). Therefore, I am wondering where is this r. 

Thanks!

**Comment by zhaojw1998** [comment]
> Hi,
> 
> Thanks for making the source open, it is really a great chance to learn from you!
> 
> After reading the paper, I got a simple question about the dilated transformer module. In the paper, it seemed that there's a dilation rate r that grows exponentially from 2^0 to 2^8, and the r are different across the layers. But when I read the code, I found that the idx variable used for initializing Demixed_DilatedTransformerModel was not utilized in dilation (please correct me if i am wrong). Therefore, I am wondering where is this r.
> 
> Thanks!

Hi,

In our implementation, the dilation rate **_r_** = **_2_**^**_layer_**, where **_layer_** ranges from 0 to 8. 
When initializing the dilated Transformer layers, however, there is no need to initialize this dilation rate. Dilation is performed when calling the layers. 

Please refer to _line 64_ of [DilatedTransformer.py](https://github.com/zhaojw1998/Beat-Transformer/blob/main/code/DilatedTransformer.py). we assign argument layer=_**layer**_. This layer argument (0, 1, ..., 8) is later used in the **kv_roll( )** method (_line 74_ in [DilatedTransformerLayer.py](https://github.com/zhaojw1998/Beat-Transformer/blob/main/code/DilatedTransformerLayer.py)) to perform dilation.

Hope this helps!

**Comment by asdf2adsfad** [comment]
Thank you! This detailed answer really helped me a lot.

I would like to have a follow-up stupid question on dilation if you don't mind😂

In the paper, 

>  The dilation rate grows exponentially from 2^0 to 2^8, stretching to a receptive field of 47.51 seconds. 

Given the frame_step(as in Spleeter)=1024, sr=44100 (as in the jupyter notebook), there would be approximately 44100/1024 frame in a second.

Total frames in receptive field = 47.51 * (44100/1024), which is approximately 2^11.

Does this mean the r is 11 in the last layer? Thank you!

**Comment by zhaojw1998** [comment]
> Thank you! This detailed answer really helped me a lot.
> 
> I would like to have a follow-up stupid question on dilation if you don't mind😂
> 
> In the paper,
> 
> > The dilation rate grows exponentially from 2^0 to 2^8, stretching to a receptive field of 47.51 seconds.
> 
> Given the frame_step(as in Spleeter)=1024, sr=44100 (as in the jupyter notebook), there would be approximately 44100/1024 frame in a second.
> 
> Total frames in receptive field = 47.51 * (44100/1024), which is approximately 2^11.
> 
> Does this mean the r is 11 in the last layer? Thank you!

We have 9 layers in total. Let's use _r_ to index the layers (_r_ ranges from 0 to 8). On layer _r_, the dilation rate is 2^_r_. This means that our window encodes a frame every 2^_r_ timesteps.

The 'receptive field' in our paper refers to the accumulated receptive ranges throughout the 9 layers. Also note that we have a dilated window of size _w_=5. At layer _r_, the receptive field _R_ =  (_w_-1) * 2^_r_ + (_w_-1) *(2^_r_-1) + 1. Here, the first term (_w_-1) * 2^_r_ is contributed by the dilated window on layer _r_. The second term (_w_-1) *(2^_r_-1) is contributed by previous layers on both sides of layer _r_'s window. Let _r_=8 and _w_=5, we approximately have _R_ = 2^11.
